kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.33.1
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 8501
        hostPort: 8501
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30081
        hostPort: 30081
        listenAddress: "0.0.0.0"
        protocol: tcp
      - containerPort: 30080
        hostPort: 30080
        listenAddress: "0.0.0.0"
        protocol: tcp
  - role: worker
    image: kindest/node:v1.33.1
  - role: worker
    image: kindest/node:v1.33.1