name: Build, Push, Deploy ATS app to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: View file structure BEFORE environment file creation
        run: |
          echo "Current file structure "
          ls -a

      - name: Restore .env file
        run: echo ${{ secrets.ENV_FILE_B64 }} | base64 --decode > .env

      - name: Restore config.properties file
        run: echo ${{ secrets.CONFIG_PROPERTIES_B64 }} | base64 --decode > config.properties

      - name: Create certs folder
        run: |
          mkdir certs
          echo "Current file structure after certs folder creation"
          ls -a
          
      - name: Restore cert.pem file
        run: |
          echo "Saving cert.pem"
          echo ${{ secrets.CERT_PEM_B64 }} | base64 --decode > certs/cert.pem
          echo "Current file structure "
          ls -a

      - name: Restore key.pem file
        run: echo ${{ secrets.KEY_PEM_B64 }} | base64 --decode > certs/key.pem

      - name: View file structure AFTER environment file creation
        run: |
          echo "Current file structure "
          ls -a
          echo "certs file structure "
          ls certs -a

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ats_app:1.25

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: View file structure
        run: |
          echo "Current file structure "
          ls -a

      - name: Copy deployment file via SSH password
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "deployment/ats-deployment.yaml"
          target: "/tmp/kube-deploy"
          script: |
            mkdir -p /tmp/kube-deploy

      - name: Copy service file via SSH password
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "deployment/ats-service.yaml"
          target: "/tmp/kube-deploy"
          script: |
            mkdir -p /tmp/kube-deploy

      - name: Apply deployment with remote SSH commands
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "Successfully connected!"
            echo "SSH file structure"
            dir
            docker --version
            kind --version
            kubectl version --client --output=yaml
            kubectl get service -n ats-space
            kubectl get deployment -n ats-space
            kubectl get pods -n ats-space
            kubectl apply -f /tmp/kube-deploy/deployment/ats-deployment.yaml -n ats-space

      - name: Apply kubectl service with remote SSH commands
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "Successfully connected!"
            echo "SSH file structure"
            dir
            kubectl get service -n ats-space
            kubectl get deployment -n ats-space
            kubectl get pods -n ats-space
            kubectl apply -f /tmp/kube-deploy/deployment/ats-service.yaml -n ats-space